---
title: "Felinos"
author: "Ashley Jump"
date: '2022-06-08'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Presentación
```{r carga-paquetes, message=FALSE}
library(dplyr)
library(ggplot2)
library(plotly)
library(sf)
library(DT)
library(leaflet)
```

```{r}
# Lectura de un archivo CSV con registros de presencia de felinos en Costa Rica
felinos <-
  st_read(
    "C:/Users/gf0604-1/Dt. Geoespaciales/felinos.csv",
    options = c(
      "X_POSSIBLE_NAMES=decimalLongitude", # columna de longitud decimal
      "Y_POSSIBLE_NAMES=decimalLatitude"   # columna de latitud decimal
    ),
    quiet = TRUE
  )
```

# Tabla

```{r Tabla, echo=FALSE}
# Visualización de datos de felinos en formato tabular
felinos %>%
  select(species,
         eventDate,
         stateProvince,
         locality,
         decimalLongitude,
         decimalLatitude) %>%
  st_drop_geometry() %>%
  datatable(
    colnames = c(
      "Especie",
      "Fecha",
      "Provincia",
      "Localidad",
      "Longitud",
      "Latitud"
    ),
    options = list(
      pageLength = 10,
      language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
    )
  )
```


# Gráfico
```{r Gráfico, message=FALSE, echo=FALSE}

gráfico_barras <-
  felinos %>%
  ggplot(aes(x = species)) +
  geom_bar() 

ggplotly(gráfico_barras)
  
```

# Mapa
```{r mapa, message=FALSE, echo=FALSE}
leaflet() %>%
  addTiles() %>% # capa base de OSM
  addCircleMarkers( # capa de registros de presencia (puntos)
    data = felinos,
    stroke = F,
    radius = 4,
    fillColor = 'blue',
    fillOpacity = 1
  )
```



